version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dojo-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-dojo_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dojo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dojo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dojo-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./dojo-backend
      dockerfile: Dockerfile
    container_name: dojo-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-dojo_platform}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      JWT_EXPIRE: ${JWT_EXPIRE:-30d}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dojo-network
    volumes:
      - ./dojo-backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./dojo-platform
      dockerfile: Dockerfile
    container_name: dojo-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    depends_on:
      - backend
    networks:
      - dojo-network
    volumes:
      - ./dojo-platform:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  dojo-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: